### ISSUE TITLE
Please rename the project to avoid confusion with the official bindings

### ISSUE THREAD

**Issue by gaearon** [cgarvis/redux-react#1]
Hi!

I appreciate you building on top of Redux but I'm afraid this project is going to generate a lot of confusion because its name is very similar to the official [react-redux](https://github.com/gaearon/react-redux) bindings.

The problem is especially bad because it's very easy to type the wrong thing into the terminal and then guess why doesn't work like the [documentation](https://github.com/gaearon/react-redux). The fact that `react-redux` was originally called `redux-react` doesn't help either.

If you don't like its API, please [help us come up with a better one](https://github.com/gaearon/react-redux/issues/1). We're happy to break `react-redux` a few times while we figure it out.

Thanks for considering this request! I hope we can sort it out.

**Comment by titosrevenge** [comment]
+1

**Comment by rogozhnikoff** [comment]
+1

**Comment by gaearon** [comment]
Can I please ask you to unpublish `redux-react` NPM module? This is really confusing people, especially as we move towards 1.0 release. Thanks.

**Comment by gaearon** [comment]
Some alternative naming suggestions:

* `redux-react-simple`
* `redux-react-component`

**Comment by rafayepes** [comment]
+1

What about naming it "redux-react-bindings"? Just adding more options to the table

**Comment by mikekidder** [comment]
I hope this gets unpublished from npm and @gaearon can register name.  Too confusing..

**Comment by knowbody** [comment]
+1

**Comment by danmartinez101** [comment]
+1

**Comment by kylejaster** [comment]
+1

**Comment by jirutka** [comment]
+1

**Comment by constb** [comment]
``react-redux-alternative``- let's keep names order consistent with official lib.

**Comment by keyanzhang** [comment]
+1

**Comment by andreychev** [comment]
+1

**Comment by stooboo** [comment]
+1

**Comment by gaearon** [comment]
I wrote an email to Chris. Hoping for the issue will be solved soon!

**Comment by cgarvis** [comment]
I understand that this is confusing to users.  I'm trying to resolve this issue.  It's not as simple as just unpublishing from npm as I have at least 4 projects in production using this package and I know of 1 other teams also using it.  Unfortunately I just haven't had the bandwidth to make this happen in the last 4 days.

**Comment by gaearon** [comment]
Thank you! You can provide a gradual deprecation:

1. Publish it under a different name
1. Use `npm deprecate` to add a deprecation warning saying the official bindings are `react-redux`, but this project is moving to `<new package name>`
1. Give those projects some time to change the name in `package.json` and source files
1. Unpublish the module

Does this make sense?

**Comment by gaearon** [comment]
Also, as the first step, you can merge https://github.com/cgarvis/redux-react/pull/2 or equivalent.
This shouldn't break any consumers. :-)

Finally, I would like to ask you to keep the issue open so it's visible. Closing it while the issue is not resolved means less people seeing it as they scratch their heads.

**Comment by estk** [comment]
:+1:

**Comment by oliverturner** [comment]
@cgarvis Simply changing the reference in your `package.json` to 
```
  "dependencies": {
    ...
    "redux-react": "cgarvis/redux-react",
    ...
}
```
so that it pulls from Github directly would allow you to unpublish from npm, no?

**Comment by luiscarli** [comment]
+1

**Comment by krrg** [comment]
+1

**Comment by anishone** [comment]
+1

**Comment by kirk1h** [comment]
+1

**Comment by zrosenbauer** [comment]
+1

**Comment by timuric** [comment]
+1

**Comment by jtiemann** [comment]
+1

**Comment by chrisbutcher** [comment]
+1

**Comment by aldendaniels** [comment]
+1

**Comment by adamkdean** [comment]
+1

**Comment by MattouFP** [comment]
+1

**Comment by earthdan** [comment]
+1

**Comment by cgarvis** [comment]
Good bye redux community
